# Generated by Django 5.2.7 on 2025-10-23 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del plato')),
                ('description', models.TextField(help_text='Describe los ingredientes y preparación', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetariano')),
                ('spicy_level', models.IntegerField(choices=[(0, 'No picante'), (1, 'Poco picante'), (2, 'Medio picante'), (3, 'Muy picante')], default=0, verbose_name='Nivel de picante')),
                ('preparation_time', models.IntegerField(help_text='Tiempo en minutos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo de preparación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='first_app.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Plato del menú',
                'verbose_name_plural': 'Platos del menú',
                'ordering': ['category', 'name'],
            },
        ),
    ]
