# Generated by Django 5.2.7 on 2025-10-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
