# Generated by Django 5.2.7 on 2025-10-23 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_menu_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='category_id',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='first_app.menucategory'),
        ),
    ]
